# Generated by Django 3.0.4 on 2020-03-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_auto_20200307_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deleted',
        ),
        migrations.AddField(
            model_name='folder',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
