# Generated by Django 3.0.4 on 2020-03-11 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0005_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapi.Folder'),
        ),
    ]
