# Generated by Django 3.0.4 on 2020-03-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0006_auto_20200311_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='active',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='archived',
        ),
    ]
